version: '3'
services:
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: docretrieval-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
